name: imitation
channels:
  - pytorch
  - pytorch3d
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - hydra-core
  - pytorch==2.0.0
  - torchvision==0.15.1
  - pip:
    - pytorchvideo
    - gymnasium
    - gym
    - robomimic
    - -e git+https://github.com/ARISE-Initiative/robosuite.git@v1.4.1#egg=robosuite
    - mujoco-py