name: imitation
channels:
  - pytorch
  - pytorch3d
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - hydra-core
  - pip:
    - pytorchvideo
    - gymnasium
    - gym
    - -e git+https://github.com/columbia-ai-robotics/diffusion_policy#egg=diffusion_policy