name: imitation
channels:
  - pytorch
  - pytorch3d
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - hydra-core
  - pip:
    - pytorchvideo
    - gymnasium==0.28.1
    - gym==0.26.2
    - -e git+https://github.com/columbia-ai-robotics/diffusion_policy#egg=diffusion_policy
    - torch==1.12.1 # +cu102