max_steps: 1000
output_dir: ./output


obs_horizon: 1

num_particles_per_goal: 10
num_samples: 32
num_obst: 2
traj_len: 64
dt: 0.05
start_pose: [1.0, 0.0, 0.0]
start_quat: [0.0, 0.0, 0.0, 1.0]
target_pose: [0.0, 1.0, 0.0]
#target_rot fixed
seed: 0
opt_iters:  400

# cost sigmas
sigma_self: 0.001
sigma_coll: 0.0001
sigma_goal: 0.0007
sigma_goal_prior: 0.001
sigma_start: 0.0001
sigma_gp: 0.07


stochgpmp_params:
  num_particles_per_goal: ${num_particles_per_goal}
  num_samples: ${num_samples}
  traj_len: ${traj_len}
  opt_iters: 1 # keep 1 for visualization
  temperature: 1.
  step_size: 0.5
  sigma_start_init: 0.0001
  sigma_goal_init: 0.0001
  sigma_gp_init: 10
  sigma_start_sample: 0.0001
  sigma_goal_sample: 0.0001
  sigma_gp_sample: 0.5
  seed: ${seed}
  # tensor_args: {device: cpu, dtype: float64}

env_runner: 
  _target_: imitation.env_runner.robot_se2_runner.RobotSe2EnvRunner
  output_dir: ${output_dir}

planner:
  # _partial_: true # other parameters (env and robot_fk) will be set on code
  _target_: imitation.utils.stochgpmp.StochGPMPSE2Wrapper
  seed: ${seed}