num_episodes: 2
max_episode_steps: 100
output_dir: ./output



env_runner: 
  _target_: imitation.env_runner.kitchen_pose_runner.KitchenPoseRunner

policy:
  _target_: imitation.policy.random_policy.RandomPolicy

agent:
  _target_: imitation.agent.kitchen_agent.KitchenAgent