num_episodes: 5
output_dir: ./output

obs_dim: 5
action_dim: 2
pred_horizon: 1
obs_horizon: 1
action_horizon: 1
max_steps: 200

env_runner: 
  _target_: imitation.env_runner.pusht_diffusion_runner.PushtDiffusionRunner
  output_dir: ${output_dir}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  pred_horizon: ${pred_horizon}
  obs_horizon: ${obs_horizon}
  action_horizon: ${action_horizon}
  max_steps: ${max_steps}


policy:
  _target_: imitation.policy.mlp_policy.MLPPolicy
  model:
    _target_: imitation.model.mlp.MLPNet
    input_dim: ${obs_dim}
    output_dim: ${action_dim}
    hidden_dims: [256, 256, 128, 32, 128, 256]
    activation:
      _target_: torch.nn.ReLU
    output_activation: 
      _target_: torch.nn.Identity
  env:
    _target_: imitation.env.pusht_env.PushtEnv
    obs_dim: ${obs_dim}
    action_dim: ${action_dim}
    pred_horizon: ${pred_horizon}
    obs_horizon: ${obs_horizon}
    action_horizon: ${action_horizon}
    max_steps: ${max_steps}
  dataset:
    _target_: imitation.dataset.pusht_state_dataset.PushTStateDataset
    dataset_path: ./pusht_cchi_v7_replay.zarr.zip
    pred_horizon: ${pred_horizon}
    obs_horizon: ${obs_horizon}
    action_horizon: ${action_horizon}
  ckpt_path: ./weights/mlp_last.pt1000_ep.pt


agent:
  _target_: imitation.agent.pusht_agent.PushTAgent