num_episodes: 2
output_dir: ./output

obs_dim: 5
action_dim: 2
pred_horizon: 16
obs_horizon: 2
action_horizon: 8
max_steps: 200

env_runner: 
  _target_: imitation.env_runner.pusht_diffusion_runner.PushtDiffusionRunner
  output_dir: ${output_dir}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  pred_horizon: ${pred_horizon}
  obs_horizon: ${obs_horizon}
  action_horizon: ${action_horizon}
  max_steps: ${max_steps}


policy:
  _target_: imitation.policy.diffusion_policy.DiffusionUnet1DPolicy
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  pred_horizon: ${pred_horizon}
  obs_horizon: ${obs_horizon}
  action_horizon: ${action_horizon}
  num_diffusion_iters: 100

agent:
  _target_: imitation.agent.pusht_agent.PushTAgent