num_episodes: 2
max_steps: 1000
output_dir: ./output


env_runner: 
  _target_: imitation.env_runner.robot_se2_runner.RobotSe2EnvRunner
  output_dir: ${output_dir}

policy:
  _target_: imitation.policy.random_policy.RandomPolicy

agent:
  _target_: imitation.agent.robot_se2_agent.Se2Agent