num_episodes: 1
output_dir: ./output

# Environment
obs_dim: 19
action_dim: 7
pred_horizon: 16


model_path: ./weights/lift_vae_last.pt

max_steps: 5000

obs_keys: &obs_keys ['object', 'robot0_eef_pos', 'robot0_eef_quat', 'robot0_gripper_qpos']


env_runner: 
  _target_: imitation.env_runner.robomimic_lowdim_runner.RobomimicEnvRunner
  output_dir: ${output_dir}
  env:
    _target_: imitation.env.robomimic_lowdim_wrapper.RobomimicLowdimWrapper
    max_steps: ${max_steps}
    task: "Lift"
policy:
  _target_: imitation.policy.vae_policy.VAEPolicy
  model:
    _target_: imitation.model.vae.VAE
    # input is action_dim*obs_horizon
    input_dim: 112 # 8*5
    hidden_dims: [64, 32, 16, 8]
    latent_dim: 4
  env: ${env_runner.env}
  dataset:
    _target_: imitation.dataset.robomimic_lowdim_dataset.RobomimicLowdimDataset
    dataset_path: ./data/lift_low_dim_v141.hdf5
    obs_keys: *obs_keys
    pred_horizon: ${pred_horizon}
  # ckpt_path: ./weights/se2_vae_test.pt


agent:
  _target_: imitation.agent.robomimic_lowdim_agent.Se2Agent