num_episodes: 2
output_dir: ./output

# Environment
obs_dim: 5
action_dim: 2
pred_horizon: 16
obs_horizon: 2
action_horizon: 8
max_steps: 200

# Training parameters
num_epochs: 100
model_path: ./se2_diffusion_policy.pt


env_runner: 
  _target_: imitation.env_runner.robomimic_lowdim_runner.RobomimicEnvRunner
  output_dir: ${output_dir}



policy:
  _target_: imitation.policy.diffusion_policy.DiffusionUnet1DPolicy
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  pred_horizon: ${pred_horizon}
  obs_horizon: ${obs_horizon}
  action_horizon: ${action_horizon}
  num_diffusion_iters: 100
  dataset:
    _target_: imitation.dataset.robomimic_lowdim_dataset.RobomimicLowdimDataset
    dataset_path: ./data/trajs.hdf5
    pred_horizon: ${pred_horizon}
    obs_horizon: ${obs_horizon}
    action_horizon: ${action_horizon}
  # ckpt_path: 


agent:
  _target_: imitation.agent.pusht_agent.PushTAgent